### ISSUE TITLE
Game fails to launch

### ISSUE THREAD

**Issue by CosmicVoidTree** [Boxadactle/BoxLib#3]
I'm using Modrinth as a launcher, and fabric as a loader, on version 1.20.1. Upon attempt to launch the game, having the library installed makes the launch fail. It's not a mod conflict as I tested it with just the library and it still failed (the log file is from that test) Log file attached https://mclo.gs/QojjoNh#L62

**Comment by Boxadactle** [comment]
This issue has been fixed. Please update to the newest version 10.4.0 for 1.20.1.
