### ISSUE TITLE
Version downgraded?

### ISSUE THREAD

**Issue by Aceplante** [Boxadactle/BoxLib#4]
Your mod went from 11.3.2 to 10.4, which mods requiring it recognize as a downgrade aka not a valid version and crash.

forge 1.20.1

**Comment by NolanHewitt** [comment]
I noticed this as well. I just use 11.3.2, not sure if 10.4 is actually newer or just a reupload

**Comment by Boxadactle** [comment]
10.4 is for 1.20 only and was mislabeled, 11.3.2 is the correct version for 1.20.1
